//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPiServer.Commerce.Sample.Templates.Sample.Units.CartCheckout {
    
    
    public partial class MultiShipmentCheckout {
        
        /// <summary>
        /// ErrorModalModule control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.Commerce.Sample.Templates.Sample.Units.CartCheckout.SharedModules.ErrorModalModule ErrorModalModule;
        
        /// <summary>
        /// BillingAddressInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.Commerce.Sample.Templates.Sample.Units.CartCheckout.SharedModules.CartAddressView BillingAddressInfo;
        
        /// <summary>
        /// ApplyCouponsID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.Commerce.Sample.Templates.Sample.Units.CartCheckout.SharedModules.ApplyCoupons ApplyCouponsID;
        
        /// <summary>
        /// lvSplitShipment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView lvSplitShipment;
        
        /// <summary>
        /// PaymentOptionsID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.Commerce.Sample.Templates.Sample.Units.CartCheckout.SharedModules.PaymentOptions PaymentOptionsID;
        
        /// <summary>
        /// OrderSubtotal1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.Commerce.Sample.Templates.Sample.Units.CartCheckout.SharedModules.OrderSubtotalSimpleView OrderSubtotal1;
        
        /// <summary>
        /// CancelButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CancelButton;
        
        /// <summary>
        /// goToCheckout control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton goToCheckout;
        
        /// <summary>
        /// Addresses control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.Commerce.Sample.Templates.Sample.Units.CartCheckout.SharedModules.AddressControl Addresses;
    }
}
