//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPiServer.Commerce.Sample.Templates.Sample.Units.CartCheckout.SharedModules {
    
    
    public partial class SplitShipmentControl {
               
        /// <summary>
        /// LineItemsID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.Commerce.Sample.Templates.Sample.Units.CartCheckout.SharedModules.LineItemsMultiView LineItemsID;
        
        /// <summary>
        /// ShippingAddressInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.Commerce.Sample.Templates.Sample.Units.CartCheckout.SharedModules.CartAddressView ShippingAddressInfo;
        
        /// <summary>
        /// shippingOptions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView shippingOptions;
        
        /// <summary>
        /// OrderSubtotalID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.Commerce.Sample.Templates.Sample.Units.CartCheckout.SharedModules.OrderSubtotalMultiView OrderSubtotalID;
    }
}
