//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPiServer.Commerce.Sample.Templates.Sample.Units.ProductDetail.Clothing {
    
    
    public partial class ClothingProductItemSelector {
        
        /// <summary>
        /// ProductPriceDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.Commerce.Sample.Templates.Sample.Units.ProductDetail.SharedModules.ProductInfoPricing.ProductPriceDetails ProductPriceDetails;
        
        /// <summary>
        /// colors control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList colors;
        
        /// <summary>
        /// sizes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList sizes;
        
        /// <summary>
        /// ProductPromotions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.Commerce.Sample.Templates.Sample.Units.ProductDetail.SharedModules.ProductPromotions ProductPromotions;
        
        /// <summary>
        /// AddToCart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.Commerce.Sample.Templates.Sample.Units.ProductDetail.SharedModules.AddToCart AddToCart;
        
        /// <summary>
        /// ProductWarehouseInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.Commerce.Sample.Templates.Sample.Units.ProductDetail.SharedModules.ProductWarehouseInfo ProductWarehouseInfo;
    }
}
