/**
<summary>
Restore diagram 'ApplicationSystem'
</summary>
<remarks>
Generated by Tool_ScriptDiagram2005/Tool_VarbinaryToVarcharHex
Will attempt to create [sysdiagrams] table if it doesn't already exist
</remarks>
<generated>2009-10-14 12:32</generated>
*/
PRINT '=== Tool_ScriptDiagram2005 restore diagram [ApplicationSystem] ==='
	-- If the sysdiagrams table has not been created in this database, create it!
				IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'sysdiagrams')
				BEGIN
					-- Create table script generated by Sql Server Management Studio
					-- _Assume_ this is roughly equivalent to what Sql Server/Management Studio
					-- creates the first time you add a diagram to a 2005 database
					CREATE TABLE [dbo].[sysdiagrams](
						[name] [sysname] NOT NULL,
						[principal_id] [int] NOT NULL,
						[diagram_id] [int] IDENTITY(1,1) NOT NULL,
						[version] [int] NULL,
						[definition] [varbinary](max) NULL,
					PRIMARY KEY CLUSTERED 
					(
						[diagram_id] ASC
					)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF) ,
					 CONSTRAINT [UK_principal_name] UNIQUE NONCLUSTERED 
					(
						[principal_id] ASC,
						[name] ASC
					)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF) 
					) 
					EXEC sys.sp_addextendedproperty @name=N'microsoft_database_tools_support', @value=1 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'sysdiagrams'
					PRINT '[sysdiagrams] table was created as it did not already exist'
				END
				-- Target table will now exist, if it didn't before
SET NOCOUNT ON -- Hide (1 row affected) messages
DECLARE @newid INT
DECLARE @DiagramSuffix          varchar (50)
 
SET @DiagramSuffix = ''
 
PRINT 'Create row for new diagram'
BEGIN TRY
    PRINT 'Write diagram ApplicationSystem into new row (and get [diagram_id])'
    INSERT INTO sysdiagrams ([name], [principal_id], [version], [definition]) VALUES ('ApplicationSystem'+@DiagramSuffix, 1, 1, 0x)
    SET @newid = SCOPE_IDENTITY()
END TRY
BEGIN CATCH
    PRINT 'XxXxX ' + Error_Message() + ' XxXxX'
    PRINT 'XxXxX END Tool_ScriptDiagram2005 - fix the error before running again XxXxX'
    RETURN
END CATCH
 
PRINT 'Now add all the binary data...'
BEGIN TRY
    UPDATE sysdiagrams SET [definition] .Write ( 0xD0CF11E0A1B11AE1000000000000000000000000000000003E000300FEFF0900, null, 0) WHERE diagram_id = @newid -- index:1
    UPDATE sysdiagrams SET [definition] .Write ( 0x0600000000000000000000000100000001000000000000000010000002000000, null, 0) WHERE diagram_id = @newid -- index:33
    UPDATE sysdiagrams SET [definition] .Write ( 0x01000000FEFFFFFF0000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:65
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:97
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:129
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:161
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:193
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:225
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:257
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:289
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:321
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:353
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:385
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:417
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:449
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:481
    UPDATE sysdiagrams SET [definition] .Write ( 0xFDFFFFFF0B000000FEFFFFFF0400000005000000060000000700000008000000, null, 0) WHERE diagram_id = @newid -- index:513
    UPDATE sysdiagrams SET [definition] .Write ( 0x090000000A0000000C000000FEFFFFFF0D0000000E0000000F00000010000000, null, 0) WHERE diagram_id = @newid -- index:545
    UPDATE sysdiagrams SET [definition] .Write ( 0x1100000012000000FEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:577
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:609
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:641
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:673
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:705
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:737
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:769
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:801
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:833
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:865
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:897
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:929
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:961
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:993
    UPDATE sysdiagrams SET [definition] .Write ( 0x52006F006F007400200045006E00740072007900000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1025
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1057
    UPDATE sysdiagrams SET [definition] .Write ( 0x16000500FFFFFFFFFFFFFFFF0200000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1089
    UPDATE sysdiagrams SET [definition] .Write ( 0x000000000000000000000000B00CB853004DCA0103000000401D000000000000, null, 0) WHERE diagram_id = @newid -- index:1121
    UPDATE sysdiagrams SET [definition] .Write ( 0x6600000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1153
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1185
    UPDATE sysdiagrams SET [definition] .Write ( 0x04000201FFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1217
    UPDATE sysdiagrams SET [definition] .Write ( 0x000000000000000000000000000000000000000000000000CA02000000000000, null, 0) WHERE diagram_id = @newid -- index:1249
    UPDATE sysdiagrams SET [definition] .Write ( 0x6F00000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1281
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1313
    UPDATE sysdiagrams SET [definition] .Write ( 0x040002010100000004000000FFFFFFFF00000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1345
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000000000000000000000000000000000000000C000000320C000000000000, null, 0) WHERE diagram_id = @newid -- index:1377
    UPDATE sysdiagrams SET [definition] .Write ( 0x010043006F006D0070004F0062006A0000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1409
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1441
    UPDATE sysdiagrams SET [definition] .Write ( 0x12000201FFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1473
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000000000000000000000000000000000000003D0000005F00000000000000, null, 0) WHERE diagram_id = @newid -- index:1505
    UPDATE sysdiagrams SET [definition] .Write ( 0x0100000002000000030000000400000005000000060000000700000008000000, null, 0) WHERE diagram_id = @newid -- index:1537
    UPDATE sysdiagrams SET [definition] .Write ( 0x090000000A0000000B000000FEFFFFFF0D0000000E0000000F00000010000000, null, 0) WHERE diagram_id = @newid -- index:1569
    UPDATE sysdiagrams SET [definition] .Write ( 0x1100000012000000130000001400000015000000160000001700000018000000, null, 0) WHERE diagram_id = @newid -- index:1601
    UPDATE sysdiagrams SET [definition] .Write ( 0x190000001A0000001B0000001C0000001D0000001E0000001F00000020000000, null, 0) WHERE diagram_id = @newid -- index:1633
    UPDATE sysdiagrams SET [definition] .Write ( 0x2100000022000000230000002400000025000000260000002700000028000000, null, 0) WHERE diagram_id = @newid -- index:1665
    UPDATE sysdiagrams SET [definition] .Write ( 0x290000002A0000002B0000002C0000002D0000002E0000002F00000030000000, null, 0) WHERE diagram_id = @newid -- index:1697
    UPDATE sysdiagrams SET [definition] .Write ( 0x3100000032000000330000003400000035000000360000003700000038000000, null, 0) WHERE diagram_id = @newid -- index:1729
    UPDATE sysdiagrams SET [definition] .Write ( 0x390000003A0000003B0000003C000000FEFFFFFF3E000000FEFFFFFF40000000, null, 0) WHERE diagram_id = @newid -- index:1761
    UPDATE sysdiagrams SET [definition] .Write ( 0x4100000042000000430000004400000045000000460000004700000048000000, null, 0) WHERE diagram_id = @newid -- index:1793
    UPDATE sysdiagrams SET [definition] .Write ( 0x490000004A0000004B0000004C0000004D0000004E0000004F00000050000000, null, 0) WHERE diagram_id = @newid -- index:1825
    UPDATE sysdiagrams SET [definition] .Write ( 0x5100000052000000530000005400000055000000560000005700000058000000, null, 0) WHERE diagram_id = @newid -- index:1857
    UPDATE sysdiagrams SET [definition] .Write ( 0x590000005A0000005B0000005C0000005D0000005E0000005F00000060000000, null, 0) WHERE diagram_id = @newid -- index:1889
    UPDATE sysdiagrams SET [definition] .Write ( 0x61000000620000006300000064000000FEFFFFFFFEFFFFFF6700000068000000, null, 0) WHERE diagram_id = @newid -- index:1921
    UPDATE sysdiagrams SET [definition] .Write ( 0x690000006A0000006B0000006C0000006D0000006E0000006F00000070000000, null, 0) WHERE diagram_id = @newid -- index:1953
    UPDATE sysdiagrams SET [definition] .Write ( 0x710000007200000073000000FEFFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:1985
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:2017
    UPDATE sysdiagrams SET [definition] .Write ( 0x000430000A1E100C05000080130000000F00FFFF13000000007D0000947A0000, null, 0) WHERE diagram_id = @newid -- index:2049
    UPDATE sysdiagrams SET [definition] .Write ( 0x9B5C0000A87E000051610000FAF1FFFF27E4FFFFDE805B10F195D011B0A000AA, null, 0) WHERE diagram_id = @newid -- index:2081
    UPDATE sysdiagrams SET [definition] .Write ( 0x00BDCB5C000008003000000000020000030000003C006B000000090000000000, null, 0) WHERE diagram_id = @newid -- index:2113
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000D9E6B0E91C81D011AD5100A0C90F5739F43B7F847F61C74385352986E1D5, null, 0) WHERE diagram_id = @newid -- index:2145
    UPDATE sysdiagrams SET [definition] .Write ( 0x52F8A0327DB2D86295428D98273C25A2DA2D0000280043000000000000005344, null, 0) WHERE diagram_id = @newid -- index:2177
    UPDATE sysdiagrams SET [definition] .Write ( 0x4DD2011FD1118E63006097D2DF4834C9D2777977D811907000065B840D9C0000, null, 0) WHERE diagram_id = @newid -- index:2209
    UPDATE sysdiagrams SET [definition] .Write ( 0x2800430000000000000051444DD2011FD1118E63006097D2DF4834C9D2777977, null, 0) WHERE diagram_id = @newid -- index:2241
    UPDATE sysdiagrams SET [definition] .Write ( 0xD811907000065B840D9C07000000D80100000087010000003400A50900000700, null, 0) WHERE diagram_id = @newid -- index:2273
    UPDATE sysdiagrams SET [definition] .Write ( 0x008001000000A8020000008000000B0000805363684772696400460500002C01, null, 0) WHERE diagram_id = @newid -- index:2305
    UPDATE sysdiagrams SET [definition] .Write ( 0x00004170706C69636174696F6E0000003800A5090000070000800E000000AE02, null, 0) WHERE diagram_id = @newid -- index:2337
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000008000000E0000805363684772696400162600002C0100004170706C6963, null, 0) WHERE diagram_id = @newid -- index:2369
    UPDATE sysdiagrams SET [definition] .Write ( 0x6174696F6E4C6F67000000008000A5090000070000800F000000520000000180, null, 0) WHERE diagram_id = @newid -- index:2401
    UPDATE sysdiagrams SET [definition] .Write ( 0x000057000080436F6E74726F6C0099190000DB04000052656C6174696F6E7368, null, 0) WHERE diagram_id = @newid -- index:2433
    UPDATE sysdiagrams SET [definition] .Write ( 0x69702027464B5F4170706C69636174696F6E4C6F675F4170706C69636174696F, null, 0) WHERE diagram_id = @newid -- index:2465
    UPDATE sysdiagrams SET [definition] .Write ( 0x6E27206265747765656E20274170706C69636174696F6E2720616E6420274170, null, 0) WHERE diagram_id = @newid -- index:2497
    UPDATE sysdiagrams SET [definition] .Write ( 0x706C69636174696F6E4C6F67270000002800B501000007000080100000003100, null, 0) WHERE diagram_id = @newid -- index:2529
    UPDATE sysdiagrams SET [definition] .Write ( 0x00006D00000002800000436F6E74726F6C00431800002107000000003800A509, null, 0) WHERE diagram_id = @newid -- index:2561
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000700008011000000AE020000008000000E0000805363684772696400DC05, null, 0) WHERE diagram_id = @newid -- index:2593
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000AE150000436F6D6D6F6E53657474696E6773000000004800A50900000700, null, 0) WHERE diagram_id = @newid -- index:2625
    UPDATE sysdiagrams SET [definition] .Write ( 0x008012000000D0020000008000001F0000805363684772696400AC2600002823, null, 0) WHERE diagram_id = @newid -- index:2657
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000536368656D6156657273696F6E5F4170706C69636174696F6E5379737465, null, 0) WHERE diagram_id = @newid -- index:2689
    UPDATE sysdiagrams SET [definition] .Write ( 0x6D0000002400A501000007000080130000009F00000002800000436F6E74726F, null, 0) WHERE diagram_id = @newid -- index:2721
    UPDATE sysdiagrams SET [definition] .Write ( 0x6C00ACFFFFFFAFF7FFFF00000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:2753
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:2785
    UPDATE sysdiagrams SET [definition] .Write ( 0x21433412080000007F150000BE10000078563412070000001401000041007000, null, 0) WHERE diagram_id = @newid -- index:2817
    UPDATE sysdiagrams SET [definition] .Write ( 0x70006C00690063006100740069006F006E0000006C0053006500720076006500, null, 0) WHERE diagram_id = @newid -- index:2849
    UPDATE sysdiagrams SET [definition] .Write ( 0x72002E00530071006C0045006E0075006D002C00200056006500720073006900, null, 0) WHERE diagram_id = @newid -- index:2881
    UPDATE sysdiagrams SET [definition] .Write ( 0x6F006E003D0039002E0030002E003200340032002E0030002C00200043007500, null, 0) WHERE diagram_id = @newid -- index:2913
    UPDATE sysdiagrams SET [definition] .Write ( 0x6C0074007500720065003D006E00650075007400720061006C002C0020005000, null, 0) WHERE diagram_id = @newid -- index:2945
    UPDATE sysdiagrams SET [definition] .Write ( 0x750062006C00690063004B006500790054006F006B0065006E003D0038003900, null, 0) WHERE diagram_id = @newid -- index:2977
    UPDATE sysdiagrams SET [definition] .Write ( 0x3800340035006400630064003800300038003000630063003900310000000000, null, 0) WHERE diagram_id = @newid -- index:3009
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:3041
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000010000000500000054000000, null, 0) WHERE diagram_id = @newid -- index:3073
    UPDATE sysdiagrams SET [definition] .Write ( 0x2C0000002C0000002C000000340000000000000000000000C3230000A3130000, null, 0) WHERE diagram_id = @newid -- index:3105
    UPDATE sysdiagrams SET [definition] .Write ( 0x000000002D010000070000000C000000070000001C010000BC07000054060000, null, 0) WHERE diagram_id = @newid -- index:3137
    UPDATE sysdiagrams SET [definition] .Write ( 0xD0020000840300007602000038040000460500002A03000046050000AE060000, null, 0) WHERE diagram_id = @newid -- index:3169
    UPDATE sysdiagrams SET [definition] .Write ( 0x9204000000000000010000007F150000BE100000000000000300000003000000, null, 0) WHERE diagram_id = @newid -- index:3201
    UPDATE sysdiagrams SET [definition] .Write ( 0x02000000020000001C010000E70900000000000001000000F31000002B050000, null, 0) WHERE diagram_id = @newid -- index:3233
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000000010000000100000002000000020000001C010000BC07000001000000, null, 0) WHERE diagram_id = @newid -- index:3265
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000000F31000001A0300000000000000000000000000000200000002000000, null, 0) WHERE diagram_id = @newid -- index:3297
    UPDATE sysdiagrams SET [definition] .Write ( 0x1C010000BC0700000000000000000000342B00000A2000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:3329
    UPDATE sysdiagrams SET [definition] .Write ( 0x0D00000004000000040000001C010000BC07000024090000A005000078563412, null, 0) WHERE diagram_id = @newid -- index:3361
    UPDATE sysdiagrams SET [definition] .Write ( 0x040000006000000001000000010000000B000000000000000100000002000000, null, 0) WHERE diagram_id = @newid -- index:3393
    UPDATE sysdiagrams SET [definition] .Write ( 0x030000000400000005000000060000000700000008000000090000000A000000, null, 0) WHERE diagram_id = @newid -- index:3425
    UPDATE sysdiagrams SET [definition] .Write ( 0x04000000640062006F0000000C0000004100700070006C006900630061007400, null, 0) WHERE diagram_id = @newid -- index:3457
    UPDATE sysdiagrams SET [definition] .Write ( 0x69006F006E0000002143341208000000BC1900007D1E00007856341207000000, null, 0) WHERE diagram_id = @newid -- index:3489
    UPDATE sysdiagrams SET [definition] .Write ( 0x140100004100700070006C00690063006100740069006F006E004C006F006700, null, 0) WHERE diagram_id = @newid -- index:3521
    UPDATE sysdiagrams SET [definition] .Write ( 0x00003B2A00000080D20100000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:3553
    UPDATE sysdiagrams SET [definition] .Write ( 0x000000000000000029B23A2E00000080D001000000000000276DCD2E00000080, null, 0) WHERE diagram_id = @newid -- index:3585
    UPDATE sysdiagrams SET [definition] .Write ( 0xCD01000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:3617
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000009F0F1B2E00000080, null, 0) WHERE diagram_id = @newid -- index:3649
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFF000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:3681
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:3713
    UPDATE sysdiagrams SET [definition] .Write ( 0x366DCD2E00000080B56FCD2E00000080E2010000000000000000000001000000, null, 0) WHERE diagram_id = @newid -- index:3745
    UPDATE sysdiagrams SET [definition] .Write ( 0x05000000540000002C0000002C0000002C000000340000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:3777
    UPDATE sysdiagrams SET [definition] .Write ( 0x96240000DE200000000000002D0100000D0000000C000000070000001C010000, null, 0) WHERE diagram_id = @newid -- index:3809
    UPDATE sysdiagrams SET [definition] .Write ( 0xBC07000054060000D0020000840300007602000038040000460500002A030000, null, 0) WHERE diagram_id = @newid -- index:3841
    UPDATE sysdiagrams SET [definition] .Write ( 0x46050000AE060000920400000000000001000000BC1900007D1E000000000000, null, 0) WHERE diagram_id = @newid -- index:3873
    UPDATE sysdiagrams SET [definition] .Write ( 0x0B0000000B00000002000000020000001C0100003F0C00000000000001000000, null, 0) WHERE diagram_id = @newid -- index:3905
    UPDATE sysdiagrams SET [definition] .Write ( 0xC71100001008000000000000020000000200000002000000020000001C010000, null, 0) WHERE diagram_id = @newid -- index:3937
    UPDATE sysdiagrams SET [definition] .Write ( 0xBC0700000100000000000000C7110000ED030000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:3969
    UPDATE sysdiagrams SET [definition] .Write ( 0x02000000020000001C010000BC0700000000000000000000072C0000DE200000, null, 0) WHERE diagram_id = @newid -- index:4001
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000000000000000D00000004000000040000001C010000BC07000024090000, null, 0) WHERE diagram_id = @newid -- index:4033
    UPDATE sysdiagrams SET [definition] .Write ( 0xA005000078563412040000006600000001000000010000000B00000000000000, null, 0) WHERE diagram_id = @newid -- index:4065
    UPDATE sysdiagrams SET [definition] .Write ( 0x0100000002000000030000000400000005000000060000000700000008000000, null, 0) WHERE diagram_id = @newid -- index:4097
    UPDATE sysdiagrams SET [definition] .Write ( 0x090000000A00000004000000640062006F0000000F0000004100700070006C00, null, 0) WHERE diagram_id = @newid -- index:4129
    UPDATE sysdiagrams SET [definition] .Write ( 0x690063006100740069006F006E004C006F006700000002000B00C51A00007206, null, 0) WHERE diagram_id = @newid -- index:4161
    UPDATE sysdiagrams SET [definition] .Write ( 0x000016260000720600000000000002000000F0F0F00000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:4193
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000100000010000000000000004318000021070000551000005801, null, 0) WHERE diagram_id = @newid -- index:4225
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000320000000100000200005510000058010000020000000000FFFFFF000800, null, 0) WHERE diagram_id = @newid -- index:4257
    UPDATE sysdiagrams SET [definition] .Write ( 0x008001000000150001000000900144420100065461686F6D611D0046004B005F, null, 0) WHERE diagram_id = @newid -- index:4289
    UPDATE sysdiagrams SET [definition] .Write ( 0x004100700070006C00690063006100740069006F006E004C006F0067005F0041, null, 0) WHERE diagram_id = @newid -- index:4321
    UPDATE sysdiagrams SET [definition] .Write ( 0x00700070006C00690063006100740069006F006E0021433412080000005B1A00, null, 0) WHERE diagram_id = @newid -- index:4353
    UPDATE sysdiagrams SET [definition] .Write ( 0x00A50D000078563412070000001401000043006F006D006D006F006E00530065, null, 0) WHERE diagram_id = @newid -- index:4385
    UPDATE sysdiagrams SET [definition] .Write ( 0x007400740069006E0067007300000072007600650072002E00530071006C0045, null, 0) WHERE diagram_id = @newid -- index:4417
    UPDATE sysdiagrams SET [definition] .Write ( 0x006E0075006D002C002000560065007200730069006F006E003D0039002E0030, null, 0) WHERE diagram_id = @newid -- index:4449
    UPDATE sysdiagrams SET [definition] .Write ( 0x002E003200340032002E0030002C002000430075006C0074007500720065003D, null, 0) WHERE diagram_id = @newid -- index:4481
    UPDATE sysdiagrams SET [definition] .Write ( 0x006E00650075007400720061006C002C0020005000750062006C00690063004B, null, 0) WHERE diagram_id = @newid -- index:4513
    UPDATE sysdiagrams SET [definition] .Write ( 0x006500790054006F006B0065006E003D00380039003800340035006400630064, null, 0) WHERE diagram_id = @newid -- index:4545
    UPDATE sysdiagrams SET [definition] .Write ( 0x0038003000380030006300630039003100000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:4577
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:4609
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000100000005000000540000002C0000002C0000002C0000, null, 0) WHERE diagram_id = @newid -- index:4641
    UPDATE sysdiagrams SET [definition] .Write ( 0x003400000000000000000000009624000077140000000000002D010000070000, null, 0) WHERE diagram_id = @newid -- index:4673
    UPDATE sysdiagrams SET [definition] .Write ( 0x000C000000070000001C010000BC07000054060000D002000084030000760200, null, 0) WHERE diagram_id = @newid -- index:4705
    UPDATE sysdiagrams SET [definition] .Write ( 0x0038040000460500002A03000046050000AE0600009204000000000000010000, null, 0) WHERE diagram_id = @newid -- index:4737
    UPDATE sysdiagrams SET [definition] .Write ( 0x005B1A0000A50D000000000000040000000400000002000000020000001C0100, null, 0) WHERE diagram_id = @newid -- index:4769
    UPDATE sysdiagrams SET [definition] .Write ( 0x00A80C00000000000001000000C7110000FF0500000000000001000000010000, null, 0) WHERE diagram_id = @newid -- index:4801
    UPDATE sysdiagrams SET [definition] .Write ( 0x0002000000020000001C010000BC0700000100000000000000C7110000ED0300, null, 0) WHERE diagram_id = @newid -- index:4833
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000002000000020000001C010000BC070000000000, null, 0) WHERE diagram_id = @newid -- index:4865
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000072C0000DE20000000000000000000000D00000004000000040000, null, 0) WHERE diagram_id = @newid -- index:4897
    UPDATE sysdiagrams SET [definition] .Write ( 0x001C010000BC07000024090000A0050000785634120400000066000000010000, null, 0) WHERE diagram_id = @newid -- index:4929
    UPDATE sysdiagrams SET [definition] .Write ( 0x00010000000B0000000000000001000000020000000300000004000000050000, null, 0) WHERE diagram_id = @newid -- index:4961
    UPDATE sysdiagrams SET [definition] .Write ( 0x00060000000700000008000000090000000A00000004000000640062006F0000, null, 0) WHERE diagram_id = @newid -- index:4993
    UPDATE sysdiagrams SET [definition] .Write ( 0x000F00000043006F006D006D006F006E00530065007400740069006E00670073, null, 0) WHERE diagram_id = @newid -- index:5025
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000021433412080000003F200000C80E000078563412070000001401000053, null, 0) WHERE diagram_id = @newid -- index:5057
    UPDATE sysdiagrams SET [definition] .Write ( 0x006300680065006D006100560065007200730069006F006E005F004100700070, null, 0) WHERE diagram_id = @newid -- index:5089
    UPDATE sysdiagrams SET [definition] .Write ( 0x006C00690063006100740069006F006E00530079007300740065006D0000003D, null, 0) WHERE diagram_id = @newid -- index:5121
    UPDATE sysdiagrams SET [definition] .Write ( 0x006E00650075007400720061006C002C0020005000750062006C00690063004B, null, 0) WHERE diagram_id = @newid -- index:5153
    UPDATE sysdiagrams SET [definition] .Write ( 0x006500790054006F006B0065006E003D00620037003700610035006300350036, null, 0) WHERE diagram_id = @newid -- index:5185
    UPDATE sysdiagrams SET [definition] .Write ( 0x0031003900330034006500300038003900000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:5217
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:5249
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:5281
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000010000000500000054, null, 0) WHERE diagram_id = @newid -- index:5313
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000002C0000002C0000002C0000003400000000000000000000009624000077, null, 0) WHERE diagram_id = @newid -- index:5345
    UPDATE sysdiagrams SET [definition] .Write ( 0x140000000000002D010000070000000C000000070000001C010000BC07000054, null, 0) WHERE diagram_id = @newid -- index:5377
    UPDATE sysdiagrams SET [definition] .Write ( 0x060000D0020000840300007602000038040000460500002A03000046050000AE, null, 0) WHERE diagram_id = @newid -- index:5409
    UPDATE sysdiagrams SET [definition] .Write ( 0x0600009204000000000000010000003F200000C80E0000000000000400000004, null, 0) WHERE diagram_id = @newid -- index:5441
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000002000000020000001C010000FF0F00000000000001000000C7110000ED, null, 0) WHERE diagram_id = @newid -- index:5473
    UPDATE sysdiagrams SET [definition] .Write ( 0x03000000000000000000000000000002000000020000001C010000BC07000001, null, 0) WHERE diagram_id = @newid -- index:5505
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000000000000C7110000ED0300000000000000000000000000000200000002, null, 0) WHERE diagram_id = @newid -- index:5537
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000001C010000BC0700000000000000000000072C0000DE2000000000000000, null, 0) WHERE diagram_id = @newid -- index:5569
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000D00000004000000040000001C010000BC07000024090000A005000078, null, 0) WHERE diagram_id = @newid -- index:5601
    UPDATE sysdiagrams SET [definition] .Write ( 0x563412040000008800000001000000010000000B000000000000000100000002, null, 0) WHERE diagram_id = @newid -- index:5633
    UPDATE sysdiagrams SET [definition] .Write ( 0x000000030000000400000005000000060000000700000008000000090000000A, null, 0) WHERE diagram_id = @newid -- index:5665
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000004000000640062006F0000002000000053006300680065006D00610056, null, 0) WHERE diagram_id = @newid -- index:5697
    UPDATE sysdiagrams SET [definition] .Write ( 0x0065007200730069006F006E005F004100700070006C00690063006100740069, null, 0) WHERE diagram_id = @newid -- index:5729
    UPDATE sysdiagrams SET [definition] .Write ( 0x006F006E00530079007300740065006D000000000200008B390000C302000002, null, 0) WHERE diagram_id = @newid -- index:5761
    UPDATE sysdiagrams SET [definition] .Write ( 0x0064000000FFFFFF0000000000000000003A0001000000900174B70100065461, null, 0) WHERE diagram_id = @newid -- index:5793
    UPDATE sysdiagrams SET [definition] .Write ( 0x686F6D6136004D00650064006900610063006800610073006500200065004300, null, 0) WHERE diagram_id = @newid -- index:5825
    UPDATE sysdiagrams SET [definition] .Write ( 0x6F006D006D00650072006300650020004600720061006D00650077006F007200, null, 0) WHERE diagram_id = @newid -- index:5857
    UPDATE sysdiagrams SET [definition] .Write ( 0x6B00200035002E0031003A0020004100700070006C0069006300610074006900, null, 0) WHERE diagram_id = @newid -- index:5889
    UPDATE sysdiagrams SET [definition] .Write ( 0x6F006E002000530079007300740065006D000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:5921
    UPDATE sysdiagrams SET [definition] .Write ( 0x0100FEFF030A0000FFFFFFFF0000000000000000000000000000000017000000, null, 0) WHERE diagram_id = @newid -- index:5953
    UPDATE sysdiagrams SET [definition] .Write ( 0x4D6963726F736F66742044445320466F726D20322E300010000000456D626564, null, 0) WHERE diagram_id = @newid -- index:5985
    UPDATE sysdiagrams SET [definition] .Write ( 0x646564204F626A6563740000000000F439B27100000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:6017
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:6049
    UPDATE sysdiagrams SET [definition] .Write ( 0x0C000000FAF1FFFF27E4FFFF0100260000007300630068005F006C0061006200, null, 0) WHERE diagram_id = @newid -- index:6081
    UPDATE sysdiagrams SET [definition] .Write ( 0x65006C0073005F00760069007300690062006C0065000000010000000B000000, null, 0) WHERE diagram_id = @newid -- index:6113
    UPDATE sysdiagrams SET [definition] .Write ( 0x0300440064007300530074007200650061006D00000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:6145
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:6177
    UPDATE sysdiagrams SET [definition] .Write ( 0x160002000300000006000000FFFFFFFF00000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:6209
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000000000000000000000000000000000000003F0000007E09000000000000, null, 0) WHERE diagram_id = @newid -- index:6241
    UPDATE sysdiagrams SET [definition] .Write ( 0x53006300680065006D0061002000550044005600200044006500660061007500, null, 0) WHERE diagram_id = @newid -- index:6273
    UPDATE sysdiagrams SET [definition] .Write ( 0x6C00740000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:6305
    UPDATE sysdiagrams SET [definition] .Write ( 0x26000200FFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:6337
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000650000001600000000000000, null, 0) WHERE diagram_id = @newid -- index:6369
    UPDATE sysdiagrams SET [definition] .Write ( 0x440053005200450046002D0053004300480045004D0041002D0043004F004E00, null, 0) WHERE diagram_id = @newid -- index:6401
    UPDATE sysdiagrams SET [definition] .Write ( 0x540045004E005400530000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:6433
    UPDATE sysdiagrams SET [definition] .Write ( 0x2C0002010500000007000000FFFFFFFF00000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:6465
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000660000004403000000000000, null, 0) WHERE diagram_id = @newid -- index:6497
    UPDATE sysdiagrams SET [definition] .Write ( 0x53006300680065006D0061002000550044005600200044006500660061007500, null, 0) WHERE diagram_id = @newid -- index:6529
    UPDATE sysdiagrams SET [definition] .Write ( 0x6C007400200050006F0073007400200056003600000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:6561
    UPDATE sysdiagrams SET [definition] .Write ( 0x36000200FFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:6593
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000740000001200000000000000, null, 0) WHERE diagram_id = @newid -- index:6625
    UPDATE sysdiagrams SET [definition] .Write ( 0x1E00000000000000000000000000000000000000640000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:6657
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000010000000100000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:6689
    UPDATE sysdiagrams SET [definition] .Write ( 0x000000000000D002000006002800000041006300740069007600650054006100, null, 0) WHERE diagram_id = @newid -- index:6721
    UPDATE sysdiagrams SET [definition] .Write ( 0x62006C00650056006900650077004D006F006400650000000100000008000400, null, 0) WHERE diagram_id = @newid -- index:6753
    UPDATE sysdiagrams SET [definition] .Write ( 0x000031000000200000005400610062006C00650056006900650077004D006F00, null, 0) WHERE diagram_id = @newid -- index:6785
    UPDATE sysdiagrams SET [definition] .Write ( 0x640065003A00300000000100000008003A00000034002C0030002C0032003800, null, 0) WHERE diagram_id = @newid -- index:6817
    UPDATE sysdiagrams SET [definition] .Write ( 0x34002C0030002C0031003900380030002C0031002C0031003600320030002C00, null, 0) WHERE diagram_id = @newid -- index:6849
    UPDATE sysdiagrams SET [definition] .Write ( 0x35002C0031003000380030000000200000005400610062006C00650056006900, null, 0) WHERE diagram_id = @newid -- index:6881
    UPDATE sysdiagrams SET [definition] .Write ( 0x650077004D006F00640065003A00310000000100000008001E00000032002C00, null, 0) WHERE diagram_id = @newid -- index:6913
    UPDATE sysdiagrams SET [definition] .Write ( 0x30002C003200380034002C0030002C0032003500330035000000200000005400, null, 0) WHERE diagram_id = @newid -- index:6945
    UPDATE sysdiagrams SET [definition] .Write ( 0x610062006C00650056006900650077004D006F00640065003A00320000000100, null, 0) WHERE diagram_id = @newid -- index:6977
    UPDATE sysdiagrams SET [definition] .Write ( 0x000008001E00000032002C0030002C003200380034002C0030002C0031003900, null, 0) WHERE diagram_id = @newid -- index:7009
    UPDATE sysdiagrams SET [definition] .Write ( 0x380030000000200000005400610062006C00650056006900650077004D006F00, null, 0) WHERE diagram_id = @newid -- index:7041
    UPDATE sysdiagrams SET [definition] .Write ( 0x640065003A00330000000100000008001E00000032002C0030002C0032003800, null, 0) WHERE diagram_id = @newid -- index:7073
    UPDATE sysdiagrams SET [definition] .Write ( 0x34002C0030002C0031003900380030000000200000005400610062006C006500, null, 0) WHERE diagram_id = @newid -- index:7105
    UPDATE sysdiagrams SET [definition] .Write ( 0x56006900650077004D006F00640065003A00340000000100000008003E000000, null, 0) WHERE diagram_id = @newid -- index:7137
    UPDATE sysdiagrams SET [definition] .Write ( 0x34002C0030002C003200380034002C0030002C0031003900380030002C003100, null, 0) WHERE diagram_id = @newid -- index:7169
    UPDATE sysdiagrams SET [definition] .Write ( 0x32002C0032003300340030002C00310031002C00310034003400300000000E00, null, 0) WHERE diagram_id = @newid -- index:7201
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000E00000000000000000000000000000000000000D0020000060028000000, null, 0) WHERE diagram_id = @newid -- index:7233
    UPDATE sysdiagrams SET [definition] .Write ( 0x4100630074006900760065005400610062006C00650056006900650077004D00, null, 0) WHERE diagram_id = @newid -- index:7265
    UPDATE sysdiagrams SET [definition] .Write ( 0x6F00640065000000010000000800040000003100000020000000540061006200, null, 0) WHERE diagram_id = @newid -- index:7297
    UPDATE sysdiagrams SET [definition] .Write ( 0x6C00650056006900650077004D006F00640065003A0030000000010000000800, null, 0) WHERE diagram_id = @newid -- index:7329
    UPDATE sysdiagrams SET [definition] .Write ( 0x3A00000034002C0030002C003200380034002C0030002C003100390038003000, null, 0) WHERE diagram_id = @newid -- index:7361
    UPDATE sysdiagrams SET [definition] .Write ( 0x2C0031002C0031003600320030002C0035002C00310030003800300000002000, null, 0) WHERE diagram_id = @newid -- index:7393
    UPDATE sysdiagrams SET [definition] .Write ( 0x00005400610062006C00650056006900650077004D006F00640065003A003100, null, 0) WHERE diagram_id = @newid -- index:7425
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000100000008001E00000032002C0030002C003200380034002C0030002C00, null, 0) WHERE diagram_id = @newid -- index:7457
    UPDATE sysdiagrams SET [definition] .Write ( 0x33003100330035000000200000005400610062006C0065005600690065007700, null, 0) WHERE diagram_id = @newid -- index:7489
    UPDATE sysdiagrams SET [definition] .Write ( 0x4D006F00640065003A00320000000100000008001E00000032002C0030002C00, null, 0) WHERE diagram_id = @newid -- index:7521
    UPDATE sysdiagrams SET [definition] .Write ( 0x3200380034002C0030002C003100390038003000000020000000540061006200, null, 0) WHERE diagram_id = @newid -- index:7553
    UPDATE sysdiagrams SET [definition] .Write ( 0x6C00650056006900650077004D006F00640065003A0033000000010000000800, null, 0) WHERE diagram_id = @newid -- index:7585
    UPDATE sysdiagrams SET [definition] .Write ( 0x1E00000032002C0030002C003200380034002C0030002C003100390038003000, null, 0) WHERE diagram_id = @newid -- index:7617
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000200000005400610062006C00650056006900650077004D006F0064006500, null, 0) WHERE diagram_id = @newid -- index:7649
    UPDATE sysdiagrams SET [definition] .Write ( 0x3A00340000000100000008003E00000034002C0030002C003200380034002C00, null, 0) WHERE diagram_id = @newid -- index:7681
    UPDATE sysdiagrams SET [definition] .Write ( 0x30002C0031003900380030002C00310032002C0032003300340030002C003100, null, 0) WHERE diagram_id = @newid -- index:7713
    UPDATE sysdiagrams SET [definition] .Write ( 0x31002C00310034003400300000000F0000000F000000000000004C0000000100, null, 0) WHERE diagram_id = @newid -- index:7745
    UPDATE sysdiagrams SET [definition] .Write ( 0x045101000000640062006F00000046004B005F004100700070006C0069006300, null, 0) WHERE diagram_id = @newid -- index:7777
    UPDATE sysdiagrams SET [definition] .Write ( 0x6100740069006F006E004C006F0067005F004100700070006C00690063006100, null, 0) WHERE diagram_id = @newid -- index:7809
    UPDATE sysdiagrams SET [definition] .Write ( 0x740069006F006E0000000000000000000000C402000000001000000010000000, null, 0) WHERE diagram_id = @newid -- index:7841
    UPDATE sysdiagrams SET [definition] .Write ( 0x0F000000080000000173AE083073AE080000000000000000AD07000000000011, null, 0) WHERE diagram_id = @newid -- index:7873
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000001100000000000000000000000000000000000000D00200000600280000, null, 0) WHERE diagram_id = @newid -- index:7905
    UPDATE sysdiagrams SET [definition] .Write ( 0x004100630074006900760065005400610062006C00650056006900650077004D, null, 0) WHERE diagram_id = @newid -- index:7937
    UPDATE sysdiagrams SET [definition] .Write ( 0x006F006400650000000100000008000400000031000000200000005400610062, null, 0) WHERE diagram_id = @newid -- index:7969
    UPDATE sysdiagrams SET [definition] .Write ( 0x006C00650056006900650077004D006F00640065003A00300000000100000008, null, 0) WHERE diagram_id = @newid -- index:8001
    UPDATE sysdiagrams SET [definition] .Write ( 0x003A00000034002C0030002C003200380034002C0030002C0031003900380030, null, 0) WHERE diagram_id = @newid -- index:8033
    UPDATE sysdiagrams SET [definition] .Write ( 0x002C0031002C0031003600320030002C0035002C003100300038003000000020, null, 0) WHERE diagram_id = @newid -- index:8065
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000005400610062006C00650056006900650077004D006F00640065003A0031, null, 0) WHERE diagram_id = @newid -- index:8097
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000100000008001E00000032002C0030002C003200380034002C0030002C, null, 0) WHERE diagram_id = @newid -- index:8129
    UPDATE sysdiagrams SET [definition] .Write ( 0x0033003200340030000000200000005400610062006C00650056006900650077, null, 0) WHERE diagram_id = @newid -- index:8161
    UPDATE sysdiagrams SET [definition] .Write ( 0x004D006F00640065003A00320000000100000008001E00000032002C0030002C, null, 0) WHERE diagram_id = @newid -- index:8193
    UPDATE sysdiagrams SET [definition] .Write ( 0x003200380034002C0030002C0031003900380030000000200000005400610062, null, 0) WHERE diagram_id = @newid -- index:8225
    UPDATE sysdiagrams SET [definition] .Write ( 0x006C00650056006900650077004D006F00640065003A00330000000100000008, null, 0) WHERE diagram_id = @newid -- index:8257
    UPDATE sysdiagrams SET [definition] .Write ( 0x001E00000032002C0030002C003200380034002C0030002C0031003900380030, null, 0) WHERE diagram_id = @newid -- index:8289
    UPDATE sysdiagrams SET [definition] .Write ( 0x000000200000005400610062006C00650056006900650077004D006F00640065, null, 0) WHERE diagram_id = @newid -- index:8321
    UPDATE sysdiagrams SET [definition] .Write ( 0x003A00340000000100000008003E00000034002C0030002C003200380034002C, null, 0) WHERE diagram_id = @newid -- index:8353
    UPDATE sysdiagrams SET [definition] .Write ( 0x0030002C0031003900380030002C00310032002C0032003300340030002C0031, null, 0) WHERE diagram_id = @newid -- index:8385
    UPDATE sysdiagrams SET [definition] .Write ( 0x0031002C00310034003400300000001200000012000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:8417
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000000000000D0020000060028000000410063007400690076006500540061, null, 0) WHERE diagram_id = @newid -- index:8449
    UPDATE sysdiagrams SET [definition] .Write ( 0x0062006C00650056006900650077004D006F0064006500000001000000080004, null, 0) WHERE diagram_id = @newid -- index:8481
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000031000000200000005400610062006C00650056006900650077004D006F, null, 0) WHERE diagram_id = @newid -- index:8513
    UPDATE sysdiagrams SET [definition] .Write ( 0x00640065003A00300000000100000008003A00000034002C0030002C00320038, null, 0) WHERE diagram_id = @newid -- index:8545
    UPDATE sysdiagrams SET [definition] .Write ( 0x0034002C0030002C0031003900380030002C0031002C0031003600320030002C, null, 0) WHERE diagram_id = @newid -- index:8577
    UPDATE sysdiagrams SET [definition] .Write ( 0x0035002C0031003000380030000000200000005400610062006C006500560069, null, 0) WHERE diagram_id = @newid -- index:8609
    UPDATE sysdiagrams SET [definition] .Write ( 0x00650077004D006F00640065003A00310000000100000008001E00000032002C, null, 0) WHERE diagram_id = @newid -- index:8641
    UPDATE sysdiagrams SET [definition] .Write ( 0x0030002C003200380034002C0030002C00340030003900350000002000000054, null, 0) WHERE diagram_id = @newid -- index:8673
    UPDATE sysdiagrams SET [definition] .Write ( 0x00610062006C00650056006900650077004D006F00640065003A003200000001, null, 0) WHERE diagram_id = @newid -- index:8705
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000008001E00000032002C0030002C003200380034002C0030002C00310039, null, 0) WHERE diagram_id = @newid -- index:8737
    UPDATE sysdiagrams SET [definition] .Write ( 0x00380030000000200000005400610062006C00650056006900650077004D006F, null, 0) WHERE diagram_id = @newid -- index:8769
    UPDATE sysdiagrams SET [definition] .Write ( 0x00640065003A00330000000100000008001E00000032002C0030002C00320038, null, 0) WHERE diagram_id = @newid -- index:8801
    UPDATE sysdiagrams SET [definition] .Write ( 0x0034002C0030002C0031003900380030000000200000005400610062006C0065, null, 0) WHERE diagram_id = @newid -- index:8833
    UPDATE sysdiagrams SET [definition] .Write ( 0x0056006900650077004D006F00640065003A00340000000100000008003E0000, null, 0) WHERE diagram_id = @newid -- index:8865
    UPDATE sysdiagrams SET [definition] .Write ( 0x0034002C0030002C003200380034002C0030002C0031003900380030002C0031, null, 0) WHERE diagram_id = @newid -- index:8897
    UPDATE sysdiagrams SET [definition] .Write ( 0x0032002C0032003300340030002C00310031002C003100340034003000000013, null, 0) WHERE diagram_id = @newid -- index:8929
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000001300000000000000080000000172AE08F072AE080000000000000000E4, null, 0) WHERE diagram_id = @newid -- index:8961
    UPDATE sysdiagrams SET [definition] .Write ( 0x070000000000050000000F000000010000000E00000057000000660000000000, null, 0) WHERE diagram_id = @newid -- index:8993
    UPDATE sysdiagrams SET [definition] .Write ( 0x010003000000000000000C0000000B0000004E61BC0000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:9025
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:9057
    UPDATE sysdiagrams SET [definition] .Write ( 0xDBE6B0E91C81D011AD5100A0C90F57390000020030D4B653004DCA0102020000, null, 0) WHERE diagram_id = @newid -- index:9089
    UPDATE sysdiagrams SET [definition] .Write ( 0x1048450000000000000000000000000000000000940100004400610074006100, null, 0) WHERE diagram_id = @newid -- index:9121
    UPDATE sysdiagrams SET [definition] .Write ( 0x200053006F0075007200630065003D006D00630063002D007600690072007400, null, 0) WHERE diagram_id = @newid -- index:9153
    UPDATE sysdiagrams SET [definition] .Write ( 0x750061006C003B0049006E0069007400690061006C0020004300610074006100, null, 0) WHERE diagram_id = @newid -- index:9185
    UPDATE sysdiagrams SET [definition] .Write ( 0x6C006F0067003D00450043004600350031005F004400450056005F0051004100, null, 0) WHERE diagram_id = @newid -- index:9217
    UPDATE sysdiagrams SET [definition] .Write ( 0x5F004D00410049004E003B005000650072007300690073007400200053006500, null, 0) WHERE diagram_id = @newid -- index:9249
    UPDATE sysdiagrams SET [definition] .Write ( 0x630075007200690074007900200049006E0066006F003D005400720075006500, null, 0) WHERE diagram_id = @newid -- index:9281
    UPDATE sysdiagrams SET [definition] .Write ( 0x3B0055007300650072002000490044003D00730061003B004D0075006C007400, null, 0) WHERE diagram_id = @newid -- index:9313
    UPDATE sysdiagrams SET [definition] .Write ( 0x690070006C00650041006300740069007600650052006500730075006C007400, null, 0) WHERE diagram_id = @newid -- index:9345
    UPDATE sysdiagrams SET [definition] .Write ( 0x53006500740073003D00460061006C00730065003B005000610063006B006500, null, 0) WHERE diagram_id = @newid -- index:9377
    UPDATE sysdiagrams SET [definition] .Write ( 0x74002000530069007A0065003D0034003000390036003B004100700070006C00, null, 0) WHERE diagram_id = @newid -- index:9409
    UPDATE sysdiagrams SET [definition] .Write ( 0x690063006100740069006F006E0020004E0061006D0065003D0022004D006900, null, 0) WHERE diagram_id = @newid -- index:9441
    UPDATE sysdiagrams SET [definition] .Write ( 0x630072006F0073006F00660074002000530051004C0020005300650072007600, null, 0) WHERE diagram_id = @newid -- index:9473
    UPDATE sysdiagrams SET [definition] .Write ( 0x6500720020004D0061006E006100670065006D0065006E007400200053007400, null, 0) WHERE diagram_id = @newid -- index:9505
    UPDATE sysdiagrams SET [definition] .Write ( 0x7500640069006F002200000000800500240000004100700070006C0069006300, null, 0) WHERE diagram_id = @newid -- index:9537
    UPDATE sysdiagrams SET [definition] .Write ( 0x6100740069006F006E00530079007300740065006D0000000002260040000000, null, 0) WHERE diagram_id = @newid -- index:9569
    UPDATE sysdiagrams SET [definition] .Write ( 0x53006300680065006D006100560065007200730069006F006E005F0041007000, null, 0) WHERE diagram_id = @newid -- index:9601
    UPDATE sysdiagrams SET [definition] .Write ( 0x70006C00690063006100740069006F006E00530079007300740065006D000000, null, 0) WHERE diagram_id = @newid -- index:9633
    UPDATE sysdiagrams SET [definition] .Write ( 0x08000000640062006F000000000226001E00000043006F006D006D006F006E00, null, 0) WHERE diagram_id = @newid -- index:9665
    UPDATE sysdiagrams SET [definition] .Write ( 0x530065007400740069006E0067007300000008000000640062006F0000000002, null, 0) WHERE diagram_id = @newid -- index:9697
    UPDATE sysdiagrams SET [definition] .Write ( 0x26001E0000004100700070006C00690063006100740069006F006E004C006F00, null, 0) WHERE diagram_id = @newid -- index:9729
    UPDATE sysdiagrams SET [definition] .Write ( 0x6700000008000000640062006F00000000022400180000004100700070006C00, null, 0) WHERE diagram_id = @newid -- index:9761
    UPDATE sysdiagrams SET [definition] .Write ( 0x690063006100740069006F006E00000008000000640062006F00000001000000, null, 0) WHERE diagram_id = @newid -- index:9793
    UPDATE sysdiagrams SET [definition] .Write ( 0xD68509B3BB6BF2459AB8371664F0327008004E0000007B003100360033003400, null, 0) WHERE diagram_id = @newid -- index:9825
    UPDATE sysdiagrams SET [definition] .Write ( 0x43004400440037002D0030003800380038002D0034003200450033002D003900, null, 0) WHERE diagram_id = @newid -- index:9857
    UPDATE sysdiagrams SET [definition] .Write ( 0x4600410032002D00420036004400330032003500360033004200390031004400, null, 0) WHERE diagram_id = @newid -- index:9889
    UPDATE sysdiagrams SET [definition] .Write ( 0x7D00000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:9921
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:9953
    UPDATE sysdiagrams SET [definition] .Write ( 0x010003000000000000000C0000000B0000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:9985
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10017
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10049
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10081
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10113
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10145
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10177
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10209
    UPDATE sysdiagrams SET [definition] .Write ( 0x62885214, null, 0) WHERE diagram_id = @newid -- index:10241
 
    PRINT '=== Finished writing diagram id ' + CAST(@newid AS VARCHAR(100)) + '  ==='
    PRINT '=== Refresh your Databases-[DbName]-Database Diagrams to see the new diagram ==='
END TRY
BEGIN CATCH
    -- If we got here, the [definition] updates didn't complete, so delete the diagram row
    -- (and hope it doesn't fail!)
    DELETE FROM sysdiagrams WHERE diagram_id = @newid
    PRINT 'XxXxX ' + Error_Message() + ' XxXxX'
    PRINT 'XxXxX END Tool_ScriptDiagram2005 - fix the error before running again XxXxX'
    RETURN
END CATCH
